apiVersion: apps/v1
kind: Deployment
metadata:
  name: BookRent
  labels:
    app: BookRent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BookRent
  template:
    metadata:
      labels:
        app: BookRent
    spec:
      containers:
        - name: BookRent
          image: username/BookRent:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5